config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :reactions, only: [:create]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reaction.rb
class Reaction < ApplicationRecord
  belongs_to :to_user, class_name: "User"
  belongs_to :from_user, class_name: "User"
  
  enum status: { like: 0, dislike: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  mount_uploader :img_name, ImgNameUploader

  enum sex: { 男: 0, 女: 1}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :self_introduction, :sex, :img_name])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :self_introduction, :sex, :img_name])
  end

  def after_sign_in_path_for(resource)
    users_path
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  
  def create
    reaction = Reaction.find_or_initialize_by(to_user_id: params[:user_id], from_user_id: current_user.id)
    reaction.update_attributes(
      status: params[:reaction]
    )
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleMatch</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>-->
    <!--<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>-->
    <!--<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>-->
  </head>

  <body>
    <!--フラッシュメッセージ-->
    <% if flash[:notice] %>
      <p class="alert alert-info"><%= notice %></p>
    <% elsif flash[:alert] %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<div class="loginPage">
  <div class="container">
    <div class="loginPage_contents">
      <h1 class="h3 loginPage_contents_title">新しいマッチを見つけよう</h1>
      <%= link_to "メールアドレスでログインする", new_user_session_path, class: "btn loginPage_contents_btn" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="topPage">
  <nav class="nav">
    <ul>
      <li class="personIcon"><%= link_to(content_tag(:i, "", class: 'fas fa-2x fa-user'), user_path(current_user.id)) %></li>
      <li class="appIcon"><%= link_to image_tag("cat-hand-icon.png"), action: "index" %></li>
    </ul>
  </nav>
  <div id="tinderslide">
    <ul>
      <% @users.each do |user| %>
        <!--検索する-->
        <li data-user_id="<%= user.id %>">
          <div class="userName"><%= user.name %></div>
          <%= image_tag user.img_name.url, size: "400x400" %>
          <div class="like"></div>
          <div class="dislike"></div>
        </li>
      <% end %>
    </ul>
    <div class="noUser">近くにお相手がいません。</div>
  </div>
  <div class="actions" id="actionBtnArea">
    <%= link_to "#", class: "dislike" do %>
      <i class="fas fa-times fa-2x"></i>
    <% end %>
    <%= link_to "#", class: "like" do %>
      <i class="fas fa-heart fa-2x"></i>
    <% end %>
  </div>
</div>
<script>
  var usersNum = <%= @users.length %>
  var currentUserIndex = 0;
  var postReaction = function (user_id, reaction) {
    $ajaxSetup({
      headers: {
        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content'),
      }
    });
    $ajax({
      type: "POST",
      url: "<%= reactions_path %>",
      data: {
        user_id: user_id,
        reaction: reaction,
      },
      success: function(j_data) {
        console.log("success")
      }
    });
  }
  $("#tinderslide").jTinder({
    onDislike: function(item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'dislike')
    },
    onLike: function(item) {
      currentUserIndex++;
      checkUserNum();
      var user_id = item[0].dataset.user_id
      postReaction(user_id, 'like')
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
  });
  $('.actions .like, .actions .dislike').click(function(e){
    e.preventDefault();
    $("#tinderslide").jTinder($(this).attr('class'));
  });
  
  function checkUserNum() {
    if (currentUserIndex === usersNum) {
      $(".noUser").addClass("is-active");
      $("#actionBtnArea").addClass("is-none")
      return;
    }
  }
</script>

app/views/users/show.html.erb
<div class="usershowPage">
  <div class="container">
    <header class="header">
      <p class="header_logo">
        <%= link_to image_tag("cat-hand-icon.png"), users_path %>
      </p>
    </header>
    <div class="userInfo">
      <div class="userInfo_img">
        <%= image_tag @user.img_name.url(:thumb) %>
      </div>
      <div class="userInfo_name"><%= @user.name %></div>
      <div class="userInfo_selfIntroduction"><%= @user.self_introduction %></div>
    </div>
    <% if current_user == @user %>
      <div class="userAction">
        <div class="userAction_edit userAction_common">
          <%= link_to edit_user_registration_path do %>
            <i class="fas fa-edit fa-2x"></i>
          <% end %>
          <span>情報を編集</span>
        </div>
        <div class="userAction_logout userAction_common">
          <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fas fa-cog fa-2x"></i>
          <% end %>
          <span>ログアウト</span>
        </div>
      </div>
    <% end %>
  </div>
</div>